// website/sidebars.ts
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Autogenerate a sidebar from the docs folder structure
  sidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;